# Generated by Django 3.2.6 on 2021-09-05 10:15

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default=None, upload_to=main.models.slugify_upload),
            preserve_default=False,
        ),
    ]
